WebApplication1/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class PostController : Controller
    {
        private PostService postService;
        public PostController()
        {
            postService = new PostService();
        }
        public IActionResult Index()
        {
            var posts = postService.GetPosts();
            return View(posts);
        }

        public IActionResult PostID(int id)
        {
            var posts = postService.GetPostById(id);
            return View(posts);
        }
    }
}

WebApplication1/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class TodoController : Controller
    {
        private TodoService todoService;
        public TodoController()
        {
            todoService = new TodoService();
        }
        public IActionResult Index()
        {
            var todos = todoService.GetTodos();
            return View(todos);
        }
        public IActionResult TodoID(int id)
        {
            var todo = todoService.GetTodos().Where(x => x.Id == id).FirstOrDefault();
            return View(todo);
        }
    }
}

WebApplication1/Controllers/TodoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class TodoListController : Controller
    {
        private TodoListService todoList;
        public TodoListController()
        {
            todoList = new TodoListService();
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(int id)
        {
            var items = todoList.GetTodosList(id);
            return View(items);
        }
    }
}

WebApplication1/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class UserController : Controller
    {
        private UserService userService;
        public UserController()
        {
            userService = new UserService();
        }
        public IActionResult Index()
        {
            var items = userService.GetUsers();
            return View(items);
        }
        public IActionResult UserID(int id)
        {
            var user = userService.GetUserById(id);
            return View(user);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Hometask 4</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="">Home</a></li>
                    <li><a asp-area="" asp-controller="Post" asp-action="">Post</a></li>
                    <li><a asp-area="" asp-controller="User" asp-action="">User</a></li>
                    <li><a asp-area="" asp-controller="Todo" asp-action="">Todo</a></li>
                    <li>
                        <div class="dropdown" style="margin-top:10%">
                            <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">Queries</button>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="AmountComment" asp-action="">User</a></li>
                                <li><a asp-area="" asp-controller="CommentList" asp-action="">Comment list</a></li>
                                <li><a asp-area="" asp-controller="TodoList" asp-action="">Todo list</a></li>
                                <li><a asp-area="" asp-controller="SortingUsers" asp-action="">User by alphabets</a></li>
                                <li><a asp-area="" asp-controller="UserSelection" asp-action="">User selection</a></li>
                                <li><a asp-area="" asp-controller="PostSelection" asp-action="">Post selection</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Binary Studio Academy</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>